set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N5} [get_ports rx]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T4} [get_ports tx]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {ledout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledout[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {switch[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_clk}]
set_property PACKAGE_PIN G2 [get_ports {seg_en[7]}]
set_property PACKAGE_PIN C2 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN C1 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN H1 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN G1 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN F1 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN E1 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN G6 [get_ports {seg_en[0]}]
#一组管
set_property PACKAGE_PIN B4 [get_ports {seg_out1[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_out1[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_out1[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_out1[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_out1[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_out1[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_out1[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_out1[0]}]
#一组管
set_property PACKAGE_PIN D4 [get_ports {seg_out2[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg_out2[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg_out2[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg_out2[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg_out2[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg_out2[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg_out2[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg_out2[0]}]

#灯
set_property PACKAGE_PIN F6 [get_ports {ledout[7]}]
set_property PACKAGE_PIN G4 [get_ports {ledout[6]}]
set_property PACKAGE_PIN G3 [get_ports {ledout[5]}]
set_property PACKAGE_PIN J4 [get_ports {ledout[4]}]
set_property PACKAGE_PIN H4 [get_ports {ledout[3]}]
set_property PACKAGE_PIN J3 [get_ports {ledout[2]}]
set_property PACKAGE_PIN J2 [get_ports {ledout[1]}]
set_property PACKAGE_PIN K2 [get_ports {ledout[0]}]

set_property PACKAGE_PIN P5 [get_ports {switch[7]}]
set_property PACKAGE_PIN P4 [get_ports {switch[6]}]
set_property PACKAGE_PIN P3 [get_ports {switch[5]}]
set_property PACKAGE_PIN P2 [get_ports {switch[4]}]
set_property PACKAGE_PIN R2 [get_ports {switch[3]}]
set_property PACKAGE_PIN M4 [get_ports {switch[2]}]
set_property PACKAGE_PIN N4 [get_ports {switch[1]}]
set_property PACKAGE_PIN R1 [get_ports {switch[0]}]
set_property PACKAGE_PIN P15 [get_ports {fpga_rst}]
set_property PACKAGE_PIN P17 [get_ports {fpga_clk}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U3} [get_ports start_pg]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T5} [get_ports smallsw[0]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T3} [get_ports smallsw[1]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R3} [get_ports smallsw[2]]
