# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/c.xdc

# IP: ip/prgrom_1/prgrom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prgrom || ORIG_REF_NAME==prgrom} -quiet] -quiet
